version: '3.8'

services:
  crypto-rebal:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - CACHE_ENABLED=true
      - MAX_CACHE_SIZE=1000
    volumes:
      - ../data:/app/data
      - ../cache:/app/cache
      - ../logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - crypto-net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - crypto-net

volumes:
  redis_data:

networks:
  crypto-net:
    driver: bridge